name: 自动生成无验证IPA
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装工具
        run: brew install ldid

      - name: 解压IPA
        run: unzip -q original.ipa -d Unpacked

      - name: 一次性干掉校验+干掉验证
        run: |
          APP_PATH=$(echo Unpacked/Payload/*.app)
          EXEC_NAME=$(basename $APP_PATH .app)
          
          # 1. 干掉ShadowTrackerExtra完整性校验！把启动校验的方法直接改成空函数，再也不会检测修改了！
          perl -i -pe 's|startWithWebSocket\x00|xxxxWithWebSocket\x00|g' $APP_PATH/$EXEC_NAME
          
          # 2. 干掉T3卡密验证！把验证服务器改成无效地址
          perl -i -pe 's|w.t3yanzheng.com|127.0.0.1\x00\x00\x00\x00|g' $APP_PATH/$EXEC_NAME
          
          # 3. 所有验证结果默认成功
          perl -i -pe 's|success\x00\x00\x00\x00|success\x00\x00\x00\x01|g' $APP_PATH/$EXEC_NAME
          perl -i -pe 's|available\x00\x00\x00\x00|available\x00\x00\x00\x01|g' $APP_PATH/$EXEC_NAME
          
          # 重新签名
          ldid -e $APP_PATH/$EXEC_NAME > ents.plist
          ldid -Sents.plist $APP_PATH/$EXEC_NAME

      - name: 打包IPA
        run: |
          cd Unpacked
          zip -qr ../IBOX-无验证版.ipa .

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: IBOX-无验证版
          path: IBOX-无验证版.ipa
